### ISSUE TITLE
Problem002 Fibonacci Complexity and typo

### ISSUE THREAD

**Issue by FrankKair** [caian-gums/project-euler#1]
On `solution.md` of **Problem002**, you've said `The important thing here is: I have my fibonacci implementation that is recursive and have O(n)`, but the recursive implementation of the Fibonacci algorithm is `O(2^n)`. See [this](https://stackoverflow.com/questions/360748/computational-complexity-of-fibonacci-sequence).

And also, there's two consecutive `;` on line 10 of the solution file 😆
```cpp
LD phi_inverse = phi - 1;;
```

**Comment by caiangums** [comment]
Thanks for the feedback! I think I already corrected this.

👍
